In [1]:
import gym
import numpy as np
import random
import time

In [2]:
env=gym.make('FrozenLake-v0')

In [3]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
num_episodes=20000
max_steps_per_ep=100
lr=.1
discount_rate=.99
exploration_rate=1
max_exploration_rate=1
min_exploration_rate=.01
exploration_decay_rate=.01

In [10]:
rewards_all_ep=[]
for episode in range(num_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    for step in range(max_steps_per_ep):
        exploration_rate_threshold=random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
            
        new_state,reward,done,info=env.step(action)
        q_table[state,action]=q_table[state,action]*(1-lr)+ \
        lr*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state=new_state
        
        rewards_current_episode+=reward
        if done==True:
            break
            
    exploration_rate=min_exploration_rate+ \
    (max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    
    rewards_all_ep.append(rewards_current_episode)

rewards_per_thousand_ep=np.split(np.array(rewards_all_ep),num_episodes/1000)
count=1000
print('*****Average reward per 1000*** \n')
for r in rewards_per_thousand_ep:
    print(count,':',str(sum(r/1000)))
    count+=1000
    
print('***q-table*** \n')
print(q_table)


*****Average reward per 1000*** 

1000 : 0.5270000000000004
2000 : 0.6720000000000005
3000 : 0.6940000000000005
4000 : 0.7090000000000005
5000 : 0.6860000000000005
6000 : 0.6830000000000005
7000 : 0.6790000000000005
8000 : 0.6910000000000005
9000 : 0.6650000000000005
10000 : 0.6870000000000005
11000 : 0.6950000000000005
12000 : 0.6730000000000005
13000 : 0.6880000000000005
14000 : 0.6740000000000005
15000 : 0.6730000000000005
16000 : 0.6870000000000005
17000 : 0.7080000000000005
18000 : 0.6860000000000005
19000 : 0.6820000000000005
20000 : 0.6860000000000005
***q-table*** 

[[0.57359171 0.49112574 0.49868675 0.50461114]
 [0.30729768 0.37498046 0.32658029 0.51560053]
 [0.40508671 0.39130463 0.41223642 0.47237864]
 [0.31369582 0.29204699 0.34953572 0.45280078]
 [0.58490845 0.4356364  0.26712539 0.38059991]
 [0.         0.         0.         0.        ]
 [0.38538958 0.17639478 0.2230971  0.13601884]
 [0.         0.         0.         0.        ]
 [0.37154966 0.37179527 0.38098823 0.603643

In [11]:
for episode in range(3):
    state=env.reset()
    done=False
    print('*****EPISODE ', episode+1, '******\n\n\n')
    time.sleep(1)
    
    for step in range(max_steps_per_ep):
        env.render()
        time.sleep(.3)
        
        action=np.argmax(q_table[state,:])
        new_state, reward,done,info=env.step(action)
        
        if done:
            env.render()
            if reward==1:
                print('Reached')
                time.sleep(3)
            else:
                print('Oh No!')
                time.sleep(3)
            break
        state=new_state
env.close()

*****EPISODE  1 ******




SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
